### ISSUE TITLE
File preview popup

### ISSUE THREAD

**Issue by theopfr** [lern-fair-file-sharing/app#17]
When users clicks on a filecard they should be able to open a preview of the file. It might be difficult to implement this for every file type so let's just concentrate on images and PDFs.

**Comment by TeschNils** [comment]
File Preview of images and pdfs is on Android with no limitations possible. On IOS it is only possible to preview the first page of a pdf file, to view the whole pdf it must be downloaded.

Closing issue because all requirements are fullfilled
