### ISSUE TITLE
Create function for creating new files

### ISSUE THREAD

**Issue by theopfr** [lern-fair-file-sharing/app#20]
We need a util function that can be used to upload files to NextCloud.

**Comment by theopfr** [comment]
Please also add a function for deleting files/folders and whatever other utilities come to your mind @cma5

**Comment by cma5** [comment]
Yeah, no worries, these are the functions i'm working on right now:
![grafik](https://github.com/lern-fair-file-sharing/app/assets/68401216/93929742-1171-4609-8dfe-246fb593be6d)

**Comment by theopfr** [comment]
> Yeah, no worries, these are the functions i'm working on right now: ![grafik](https://private-user-images.githubusercontent.com/68401216/340309259-93929742-1171-4609-8dfe-246fb593be6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Mjg2MjIsIm5iZiI6MTcxODYyODMyMiwicGF0aCI6Ii82ODQwMTIxNi8zNDAzMDkyNTktOTM5Mjk3NDItMTE3MS00NjA5LThkZmUtMjQ2ZmI1OTNiZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEyNDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OTUyMGQzNTc4YzI5MTdjYzQ5OGJlNmI2NzBmMjEyYWJmY2IxMDAzNTIwNGM5NmM3YzQ2ZjkyY2Y1M2YwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XgJwUfZPDuaNOKAznaFE2Fpg_pQd-Nv7F09dZqS6sEY)

Looks great thank you! I just noticed that we also need a function for fetching a single file. For example to do an image preview we cant simply do something like ``<img href="ip:port/remote.php/dav/file/to/image.jpg />`` because to access it we also need authentication. We need this function ASAP because it also blocks two other issues that me and Nils are working on. Should we maybe do this first in another MR so that it's faster?

**Edit:** Ahh your  ``downloadFile`` is meant to do that I suppose?

**Comment by cma5** [comment]
Yep. Where do you need the file?
Should we work with https://docs.expo.dev/versions/latest/sdk/filesystem/ or store them in variables?

**Comment by cma5** [comment]
Or just return the file and storing etc is your business?

**Comment by theopfr** [comment]
Hm I'd hope that one could just link to the file as we would normally do, so no download.
Something like this: ``<img src="link/to/image.png" />``. So we'd need to fetch the file and store in encoded in a variable, like this for example:
```js
async function fetchImage() {
            const url = 'http://example.com/image.png'; // Replace with your image URL
            const username = 'your-username'; // Replace with your username
            const password = 'your-password'; // Replace with your password

            // Create the basic authentication header
            const headers = new Headers();
            headers.set('Authorization', 'Basic ' + btoa(username + ':' + password));

            try {
                // Fetch the image
                const response = await fetch(url, { headers: headers });

                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }

                // Convert the image to a blob
                const blob = await response.blob();

                // Convert the blob to a Base64 string
                const reader = new FileReader();
                reader.onloadend = function() {
                    const base64data = reader.result;
                    // Set the src attribute of the image element
                    document.getElementById('protectedImage').src = base64data;
                };
                reader.readAsDataURL(blob);
            } catch (error) {
                console.error('There has been a problem with your fetch operation:', error);
            }
        }
```

**Comment by theopfr** [comment]
Still, downloading is also an option. Not sure whats the best practice here. I think storing it in working memory as base64 is the simpler solution but downloading it is better for production applications bc it saves bandwidth and images can be acsessed without internet.
