### ISSUE TITLE
basic structure of the app with navigation bar

### ISSUE THREAD

**Issue by cma5** [lern-fair-file-sharing/app#3]
As a user I want to navigate through the app via a navigation bar.

Acceptance criteria
- Dummy page for every page we need
- Navigation bar with the relevant text and maybe even icons

![grafik](https://github.com/lern-fair-file-sharing/app/assets/68401216/4fcbfe95-ccc9-4ce1-bf9e-91f334f0480d)

![grafik](https://github.com/lern-fair-file-sharing/app/assets/68401216/fc67efd1-ccf3-4b62-a878-b17f891c5f00)

**Comment by theopfr** [comment]
Nils took care of this with th MR #8
