### ISSUE TITLE
Display tags on file cards

### ISSUE THREAD

**Issue by theopfr** [lern-fair-file-sharing/app#44]
Currently we have a gray placeholder box for where file tags should be shown. After we added file tag functionalitiy in issue #35 we can proceed and display the retrieved tags of files on the filecards.

**Comment by cma5** [comment]
I'd suggest you display the filepath where we don't have system-tags in the FileCardType

**Comment by theopfr** [comment]
> I'd suggest you display the filepath where we don't have system-tags in the FileCardType

Hmm, I've never seen that in any file system since the user always sees what folder they are in and users cant copy the path or something to open it somwhere else. But I'll keep it in mind if it looks to empty without tags.
But anyways, why wouldn't there be a tag there is always the name of there user who uploaded. Maybe inside the "Persönliche Ablage".

Shit, comes to mind that in the "Persönliche Ablage" the tutors should actually be able to choose their own tags... Probably too late now for that but let's see.
@cma5
