### ISSUE TITLE
termine mockup

### ISSUE THREAD

**Issue by cma5** [lern-fair-file-sharing/app#5]
As a user, I want to see, what's in termine.
This is just a dummy page with no functionality and should therefore be implemented quickly. It may be even not necessary to add any Elements and just load in the page as an SVG

Acceptance criteria:
![Termin Detailansicht  Gruppe _ Schüler_in](https://github.com/lern-fair-file-sharing/app/assets/68401216/6c39e5c9-aaab-439d-b7a0-b635751965b1)

**Comment by theopfr** [comment]
Let's implement this in real JSX but the buttons can be dummies and not an SVG please.

**Comment by Ashz22** [comment]
wouldnt it make more sense to make the overview as a mockup? @theopfr @cma5 
![image](https://github.com/lern-fair-file-sharing/app/assets/116884343/5128d930-6027-4df8-a375-25e6af781278)

**Comment by theopfr** [comment]
> wouldnt it make more sense to make the overview as a mockup?

Yes I think so @Ashz22
