### ISSUE TITLE
Color definition

### ISSUE THREAD

**Issue by cma5** [lern-fair-file-sharing/app#9]
As a developer, I don't want to type hex values to define the same color in different places. Therefore we should implement fixed colors, like here:

https://swairaq.medium.com/custom-colors-in-react-native-53f3591961cc

How should we name those colors.
Let's don't make a science out of it but for naming structure, here are some inspirations:
https://m2.material.io/develop/ios/components/theming/color
https://hackernoon.com/interface-colors-from-palette-to-themes

Acceptance criteria:
Globally defined colors with meaningful and intuitive names!

**Comment by Ashz22** [comment]
globally defined colors in utils/Color.ts

ready for review @cma5 

![colors](https://github.com/lern-fair-file-sharing/app/assets/116884343/52a2bbc6-8b0b-4684-99e5-9ccd9812abe7)
